# Generated by Django 4.2.1 on 2023-05-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendor'},
        ),
    ]
