# Generated by Django 4.2.1 on 2023-05-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'products'},
        ),
    ]
